ProductMergeRules:
  - rule: auto-merge -I and -O products
    command: AutoMergeIOProducts

  - rule: auto-merge NCE with CMD
    command: MergeBasedOnPattern
    pattern: '^(NCE)\d{3}.*'
    packages:
      - products:
          - CMD211
      - products:
          - CMD300

  - rule: auto-merge KCG with CMD
    command: MergeBasedOnPattern
    pattern: '^(KCG)\d{3}.*'
    packages:
      - products:
          - CMD211
      - products:
          - CMD300

  - rule: combine products
    command: CombineProducts
    packages:
      - products:
          - AE-X12BBAL
          - AY-X12BBAL
      - products:
          - CMD211
          - CRG14CL1N
      - products:
          - CMD211
          - CRG-CP1000G
